apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
        - name: server
          image: reubenemmens/app:latest
          ports:
            - containerPort: 8000
          command: ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000"]
